; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; needs 328k ram and 299k flash on T4.0
;    haeh ??? ah T4x put's all prog in ram for more speed, would need to use FLASHMEM for functions
; needs 14k ram and 323k flash on T3.6

; build gets stuck for Tlc
; does not fit on T3.2

[env]
monitor_speed = 115200
build_flags = 
    -D DECIMAL_CALL_BY_REFERENCE=1
    -D DECIMAL_GLOBAL_ROUNDING=1
    -D DECIMAL_GLOBAL_ROUNDING_ACCESS_FUNCTIONS=1
    -D DECIMAL_GLOBAL_EXCEPTION_FLAGS=1
    -D DECIMAL_GLOBAL_EXCEPTION_FLAGS_ACCESS_FUNCTIONS=1


[platformio]
; default_envs = native
default_envs = stm32f4

[env:teensy40]
platform = teensy
board = teensy36
framework = arduino
build_flags = -DENV_TEENSY -DUSB_SERIAL -DTEENSY_OPT_SMALLEST_CODE
; monitor_port = COM9

[env:stm32f4]
platform = ststm32
board = nucleo_f411re
framework = arduino
build_flags =
    -DENV_STM32F4xx -DUTF8_DISP -DBCD_MATH 
    -fno-exceptions 
    -Wl,--gc-sections
    -L${PROJECT_DIR}/lib/IntelRDFPMathLib20U1
    -lgcc111libbid-arm 
    -lm
; monitor_port = /dev/ttyACM0

[env:native]
platform = native
build_flags = 
    -DENV_NATIVE -DUSE_CURSES -DUTF8_DISP -DBCD_MATH
    -L${PROJECT_DIR}/lib/IntelRDFPMathLib20U1
    -lgcc111libbid-arm64
    -lncurses  -lm -g -O0

; debug_tool = lldb
; debug_init_break = breakpoint set --name main

; original docs say: BCD_MATH=1 USE_CURSES=1 UTF8_DISP=1
; UTF8_DISP - printed wie ein richtiges display mit irgendwelchen utf chars
; USE_CURSES - benutzt die ncurses lib für die console ausgabe
; BCD_MATH geht nicht weil ? IntelLib dann nicht mehr kompiliert

; build_unflags =  -std=gnu11 -std=gnu++14 -fno-exceptions
